package enums;

public enum RigaRiferimento {
    RIMANENZA, INTRODOTTO, ECCEDENZE_1, ECCEDENZE_2, ECCEDENZE_3,ECCEDENZE_4,TOTALE_CARICO,
    EROGATO, CALI_ANNOTATI_1, CALI_ANNOTATI_2, CALI_ANNOTATI_3,CALI_ANNOTATI_4,TOTALE_SCARICO,
    RIMANENZA_CONTABILE
}
