package it.exolab.prospetto.enums;

public enum Row {
    RIMANENZA, INTRODOTTO, ECCEDENZE_ANNOTATE_1, ECCEDENZE_ANNOTATE_2, ECCEDENZE_ANNOTATE_3, ECCEDENZE_ANNOTATE_4,
    EROGATO, CALI_ANNOTATI_1, CALI_ANNOTATI_2, CALI_ANNOTATI_3, CALI_ANNOTATI_4,
    RIMANENZA_CONTABILE
}
